### PR TITLE
Syntax highlighting for a handful of additional languages

### PR DESCRIPTION
**Pull request by BoosterOfOld**
I enabled syntax highlighting for a bunch of additional languages that I find myself often using with turbo.

- C# -- uses the CPP lexer
- A couple of Basic dialects (QBasic, QB64, VB6) + VB.NET -- I found the VB lexer superior to the BASIC lexer for all of these, as it can use both `rem` and `'` as a comment keyword, any many basic dialects use both.
- TeX -- Found the LATEX lexer superior to the TEX one even for Plain, XeTeX, and other non-latex TeXs.
- Pascal -- Pascal & Delphi/Lazarus
- SQL -- Keywords for various dialects including MySQL and MSSQL (Transact)

### CODE REVIEW

**Comment by magiblot** [comment]
Hi @BoosterOfOld! Thank you again for the contribution!

However, the commit "Syntax highlighting for SQL" does not contain the changes to `styles.cc`, so hightlighting isn't actually working.

**Comment by magiblot** [comment]
Also, in the definition of the Basic language: could it be that the comment string should be `"rem "` instead of `"rem"` because `rem` only introduces a comment when it is followed by a space? It is like this in Batch, but I don't know about Basic:
```bat
rem This is a comment.
remThis is not a comment.
```

**Comment by BoosterOfOld** [comment]
> Also, in the definition of the Basic language: could it be that the comment string should be `"rem "` instead of `"rem"` because `rem` only introduces a comment when it is followed by a space? It is like this in Batch, but I don't know about Basic:
> 
> ```batchfile
> rem This is a comment.
> remThis is not a comment.
> ```

So sorry, I forgot to push the styles.cc change for SQL. I did just now. :) And you're absolutely right about "rem " -- that's also fixed in the latest commit.

Thanks!

**Comment by magiblot** [comment]
Thank you very much! I made a few changes so that keywords would use the two keyword styles. Also, I finally set the Basic comment to `'`, since it appears to be more common than `rem` (correct me if I'm wrong).

**Pull request merged**
